### ISSUE TITLE
有關 Workflow-core 的問題.

### ISSUE THREAD

**Issue by Miles1122** [neozhu/neozhu#1]
您好:
    我是從您寫的文章 [Workflow Core + asp.net core 5.0 實現簡單審批工作流](https://iter01.com/613739.html)
而來到這個網頁的。
不知道是否有在 Blog 上面的程式碼?
一直想要理解 Workflow core 的運作方式看能不能套用到我現行想要寫的公司內部 ERP 系統中..

**Comment by neozhu** [comment]
你可以看workflow-core的sample
这个项目我做了一个简单应用你可以参考一下
https://github.com/neozhu/RazorPageCleanArchitecture
