### ISSUE TITLE
大佬加个微信？

### ISSUE THREAD

**Issue by Optkt** [neozhu/neozhu#2]
大佬我用你迁移的 blazor server 原作者的 另一个模版做了个小应用，非常吃力，希望你学习下。

ps. 就是这个
https://github.com/fullstackhero/dotnet-webapi-boilerplate

**Comment by neozhu** [comment]
我要怎么帮你呢，fullstackhero 是 blazor assembly模式，我的项目是server side模式，他那个项目有点复杂，前后端分离的

**Comment by Optkt** [comment]
我WX：  MTMxNjcwNTU2MTU=

他那个我已经升级为net7.0，转为server了，由于是新手所以很多问题。同时，那个作者不怎么更新了，想把我的应用转移到国产的Furion上

**Comment by Optkt** [comment]
我是传统制造业的，平时也就写写控制台，winform。这个网页编程完全不懂，咨询下基础问题

**Comment by neozhu** [comment]
你可以自己在youtube上找视频看，有很多

**Comment by Optkt** [comment]
好吧，谢谢大佬，有具体问题我准备好了，再回来问。
