### ISSUE TITLE
下面的url部分指向的workflow core内容是开源的吗大佬，我没找到这部分

### ISSUE THREAD

**Issue by codecodecookie** [neozhu/neozhu#3]
https://cloud.tencent.com/developer/article/1873949

**Comment by neozhu** [comment]
https://github.com/neozhu/RazorPageCleanArchitecture
这个项目我很久没有更新了

**Comment by codecodecookie** [comment]
ok ，三克油

**Comment by codecodecookie** [comment]
> https://github.com/neozhu/RazorPageCleanArchitecture 这个项目我很久没有更新了

请问这个审批的 reject 功能是否有工作流程上的回退功能如果要达到流程上的回退或者多级回退（ABC 3个审批流程节点，从C直接打回到A），该如何做呢，这对我很有帮助，谢谢大佬了

**Comment by neozhu** [comment]
具体你可以看workflow core 这个库的说明，我也只是简单的做了一个demo

**Comment by codecodecookie** [comment]
> 具体你可以看workflow core 这个库的说明，我也只是简单的做了一个demo

好的，谢谢大佬
