### ISSUE TITLE
Can't Return Relation Of One Object To Queries Or Other Commands

### ISSUE THREAD

**Issue by yadakco** [neozhu/neozhu#5]
Hi I Have an entity which is related to itself
`public class Skill : BaseAuditableEntity {
   public int? ParentID {get; set;}
  public Skill? Parent {get; set;}
  public ICollection<Skill> Children{get; set;}
}`

but in queries can't get the relation of parent just children and parentID is filled

**Comment by neozhu** [comment]
You can refer to the definition of the Superior property in the ApplicationUser entity within the project. Additionally, I would recommend avoiding adding the ICollection for the children, as this can lead to issues such as infinite loops during recursive lookups.

**Comment by yadakco** [comment]
no it use SuperiorName And In Mapping Use If It's Not Null Set SuperiorName to Superiorname of Dto But First I want that entity and my relation always it's null ex my parentId fill by relation id but my paren't isn't fill. i use relation one to many in other entity and its ok but this relation to itself and its nullable 

![dto](https://github.com/user-attachments/assets/4c5aef89-2050-4bf0-8ba1-911d2bf1b356)
![entity](https://github.com/user-attachments/assets/ed2d8c80-4239-4d6d-a479-8aadeee99027)
![configuration](https://github.com/user-attachments/assets/18fb1129-e1f9-44c6-a288-e12cc0517504)
![handler](https://github.com/user-attachments/assets/a7690212-9e60-43da-ab84-8c85d17c8eb1)

**Comment by yadakco** [comment]
but children fills and its ok
![withChildren](https://github.com/user-attachments/assets/40787502-ce7c-42e8-910c-01c234c5bfcd)
